# -*- coding: utf-8 -*-
"""prakalgo3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iKXaVIPmxsjF3pEUz5pgShci2HfyJ9R3
"""

print("@@    @@  @@@@@@   @@             @@  @@  @@@@       @@")
print("@@   @@   @@        @@           @@   @@  @@  @@     @@")
print("@@ @@     @@         @@         @@    @@  @@   @@    @@")
print("@@@       @@@@@@      @@       @@     @@  @@    @@   @@")
print("@@ @@     @@           @@     @@      @@  @@     @@  @@")
print("@@   @@   @@            @@   @@       @@  @@      @@ @@")
print("@@    @@  @@@@@@         @@@@@        @@  @@       @@@@")
angka_awal = int(input("Masukkan angka awal: "))
angka_akhir = int(input("Masukkan angka akhir: "))
if angka_awal > angka_akhir:
    angka_awal, angka_akhir = angka_akhir, angka_awal
i = angka_awal
j = angka_akhir
while i <= j:
    print(f"{i} | {j}")
    i += 1
    j -= 1

print("@@    @@  @@@@@@   @@             @@  @@  @@@@       @@")
print("@@   @@   @@        @@           @@   @@  @@  @@     @@")
print("@@ @@     @@         @@         @@    @@  @@   @@    @@")
print("@@@       @@@@@@      @@       @@     @@  @@    @@   @@")
print("@@ @@     @@           @@     @@      @@  @@     @@  @@")
print("@@   @@   @@            @@   @@       @@  @@      @@ @@")
print("@@    @@  @@@@@@         @@@@@        @@  @@       @@@@")
total_harga = float(input("Masukkan total harga belanjaan: "))
jumlah_uang = float(input("Masukkan jumlah uang yang diberikan: "))
kembalian = jumlah_uang - total_harga
if kembalian < 0:
    print("Maaf, uang yang diberikan kurang.")
else:
    print(f"Kembalian: {kembalian} Rupiah")
    lembar_uang = [50000, 20000, 10000, 5000, 1000, 500, 100, 50, 10, 5, 1]
    jumlah_lembar = [0] * len(lembar_uang)
    i = 0
    while i < len(lembar_uang):
        if kembalian >= lembar_uang[i]:
            jumlah_lembar[i] = int(kembalian / lembar_uang[i])
            kembalian %= lembar_uang[i]
        else:
            i += 1
    i = 0
    while i < len(lembar_uang):
        if jumlah_lembar[i] > 0:
            print(f"Lembar {lembar_uang[i]} Rupiah: {jumlah_lembar[i]} lembar")
        i += 1